Controllers:
  controller-0:
    partition_a: 600
    partition_b: 100
    partition_d: 100
    memory_size: 32768
    system_cores: 8
general_system_configurations:
  os_system_memory: 1024
  disk_space_allocated_to_os: 0
  os_system_cores: 2
  default_mount_point: '/mnt/extra'
